/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef sslchat_CONSTANTS_H
#define sslchat_CONSTANTS_H

#include "sslchat_types.h"

namespace sslchat {

class sslchatConstants {
 public:
  sslchatConstants();

};

extern const sslchatConstants g_sslchat_constants;

} // namespace

#endif
