/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "sslchat_constants.h"

namespace sslchat {

const sslchatConstants g_sslchat_constants;

sslchatConstants::sslchatConstants() {
}

} // namespace

